image: ubuntu:bionic

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - apt update
          - apt -y install wget lsb-release gnupg
          - sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
          - wget http://packages.osrfoundation.org/gazebo.key -O - | apt-key add -
          - apt-get update
          - apt-get -y install
            cmake pkg-config cppcheck doxygen ruby-ronn curl mercurial git g++-8
          - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8
          # lcov
          - git clone https://github.com/linux-test-project/lcov.git -b v1.14
          - cd lcov
          - make install
          - cd ..
          # Dependency: Ignition packages and sdformat
          - apt-get -y install
            libignition-cmake2-dev
            libignition-common3-dev
            libignition-math6-dev
            libignition-tools-dev
            libignition-plugin-dev
            # libsdformat9-dev
            # libignition-rendering3-dev
            # libignition-msgs5-dev
            # libignition-transport8-dev
          # SDFormat (uncomment if a specific branch is needed)
          - apt install -y
            libxml2-utils
            libtinyxml-dev
          - hg clone http://bitbucket.org/osrf/sdformat -b default
          - cd sdformat
          - mkdir build
          - cd build
          - cmake .. -DBUILD_TESTING=false
          - make -j4 install
          - cd ../..
          # Ignition msgs (uncomment if a specific branch is needed)
          - apt install -y
            libprotobuf-dev protobuf-compiler libprotoc-dev
          - hg clone http://bitbucket.org/ignitionrobotics/ign-msgs -b default
          - cd ign-msgs
          - mkdir build
          - cd build
          - cmake ..
          - make -j4 install
          - cd ../..
          # Ignition transport (uncomment if a specific branch is needed)
          - apt install -y
            libzmq3-dev uuid-dev libsqlite3-dev
          - hg clone http://bitbucket.org/ignitionrobotics/ign-transport -b default
          - cd ign-transport
          - mkdir build
          - cd build
          - cmake ..
          - make -j4 install
          - cd ../..
          # Install ign-rendering dependencies
          - apt-get -y install
            libogre-1.9-dev libogre-2.1-dev libglew-dev libfreeimage-dev freeglut3-dev libxmu-dev libxi-dev uuid-dev
          - hg clone http://bitbucket.org/ignitionrobotics/ign-rendering -b default
          - cd ign-rendering
          - mkdir build
          - cd build
          - cmake ..
          - make -j4 install
          - cd ../..
          # Ignition sensors
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=coverage -DDRI_TESTS=FALSE
          - make -j4 install
          - make test
          - make coverage
          # Use a special version of codecov for handling gcc8 output.
          - bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/4678d212cce2078bbaaf5027af0c0dafaad6a095/codecov) -X gcovout
          - make codecheck
          # Examples
          - apt-get -y install libfreeimage-dev
          - cd ..
          - cd examples/save_image
          - mkdir build
          - cd build
          - cmake ..
          - make
